<a href="https://colab.research.google.com/github/Aleem2/Mastering-ML-using-sklearn/blob/main/Sklearn_Iris__data_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analysis steps documented
1. Understand the dataset, the shape of training data and the target vector
2. What is the sample size
3. Selecting a model using the https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
4. Use template file to code the problem.

# Working on iris scikit's dataset

In [10]:
from sklearn.preprocessing import StandardScaler
#from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate
import numpy as np

# create a pipeline object
pipe = make_pipeline(
    StandardScaler(),
    svm.SVC()
)
# load the iris dataset and split it into train and test sets
X, y = load_iris(return_X_y=True)
# Understanding the data set
print('shape of X = '+ str(X.shape))
print('shape of y = '+ str(y.shape))
print(np.unique(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
# fit the whole pipeline
pipe.fit(X_train, y_train)
# we can now use it like any other estimator
acc_score=accuracy_score(pipe.predict(X_test), y_test)
result = cross_validate(pipe, X_train, y_train)  # defaults to 5-fold CV

shape of X = (150, 4)
shape of y = (150,)
[0 1 2]


In [7]:
print(result['test_score']) # The cross validates the model.

[0.95652174 0.86956522 1.         0.95454545 1.        ]


In [8]:
print(acc_score) # accuracy of test data

0.9736842105263158


In [9]:
print('Test data \n')
print(y_test)
print('Prediction on test data \n')
print(pipe.predict(X_test))

Test data 

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]
Prediction on test data 

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [11]:
# using KNN instead of SVM
from sklearn.neighbors import KNeighborsClassifier
#knn = KNeighborsClassifier()
# create a pipeline object
pipe = make_pipeline(
    StandardScaler(),
    KNeighborsClassifier()
)
# load the iris dataset and split it into train and test sets
X, y = load_iris(return_X_y=True)
# Understanding the data set
print('shape of X = '+ str(X.shape))
print('shape of y = '+ str(y.shape))
print(np.unique(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
# fit the whole pipeline
pipe.fit(X_train, y_train)
# we can now use it like any other estimator
acc_score=accuracy_score(pipe.predict(X_test), y_test)
result = cross_validate(pipe, X_train, y_train)  # defaults to 5-fold CV
print(result['test_score']) # The cross validates the model.
print(acc_score) # accuracy of test data

shape of X = (150, 4)
shape of y = (150,)
[0 1 2]
[0.95652174 0.95652174 1.         0.86363636 1.        ]
0.9736842105263158


# Rough work the cells above completes the evaluation.

In [ ]:
# importing the data
from sklearn import datasets
iris = datasets.load_iris()
X=iris.data
y=iris.target
print('shape of X = '+ str(X.shape))
print('shape of y = '+ str(y.shape))

shape of X = (150, 4)
shape of y = (150,)


In [ ]:
# splitting the data for train and test
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y)
print(X_train.shape)
print(y_train.shape)
print(np.unique(y_train))

(112, 4)
(112,)
[0 1 2]
